vich_uploader:
    db_driver: orm

    mappings:
        deliverbale:
            uri_prefix: '%app.path.deriverable_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.deriverable_files%'
            namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

